### ISSUE TITLE
Drop down cells in drop down cell

### ISSUE THREAD

**Issue by DominikBucher12** [Vkt0r/AccordionMenu#3]
Hi, I have this strange problem I can't figure out on my own... the problem is that I want to use dropdown cells in drop down cells like

DropDown
        DropDown
                -------Final cell
         DropDown
                 -------Final cell
DropDown

I tried to add SubHeader Items into the class of cell but I failed, can you point me the right way? Also I tried to attach indicators of whether the cell is expanded or collapsed, but it either worked for every cell or didn't roll back when chose other cell.. Thanks for any response, wish best coding!

**Comment by Vkt0r** [comment]
Hello Dominik,

What you want to achieve can be a little complicated to make, of course can be done. If you check out the new update I have made for the repo, I have changed the structure of the project to make it more easy to follow.

Every time a cell is expanded you need to keep the record for its position because it any other it's collapsed above the cell it `indexPath` change. You can check out in the `findParent(_:)` method.

To do what you want you have to keep an extra record of parents because can be several parents inside parents and update properly when a cell is tapped an know where is parent, subParent of child.

I hope this can help you.

**Comment by DominikBucher12** [comment]
Thank you for such fast response, I am immediatly on it
