### ISSUE TITLE
Table View reload related issue

### ISSUE THREAD

**Issue by rvishal1991** [Vkt0r/AccordionMenu#6]

**Comment by support3ds** [comment]
It seems that there is a problem expanding children in swift 2.2.
Probably it's relevant to ++ symbols.

At expandItemAtIndex function i replaced 
let insertPos = index + 2 (instead of 1) 
let indexPaths = (0..<currentSubItems.count).map { _ in NSIndexPath(forRow: insertPos, inSection: 0) } (removed ++ symbols)

I'm getting the below exception.

'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (26) must be equal to the number of rows contained in that section before the update (22), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

**Comment by support3ds** [comment]
In my case, this solution really helped me.

let insertPos = index + 1
let indexPaths = (0..<currentSubItems.count).map { idx in NSIndexPath(forRow: idx + insertPos, inSection: 0) }

**Comment by Vkt0r** [comment]
@support3ds Yes you're right I missed the ++ symbol  deprecated in Swift 2.2, I have update the project to fix it, thanks for the observation, be careful idx always go from [0, currentSubItems.count], it's better to fix it inside the closure like this:

     // position to start to insert rows.
     var insertPos = index + 1
        
     let indexPaths = (0..<currentSubItems.count).map { _ -> NSIndexPath in
            let indexPath = NSIndexPath(forRow: insertPos, inSection: 0)
            insertPos += 1
            return indexPath
     }

As the closure capture values, it could be used here.
